export const topAuthors = [
  "William Shakespeare",
  "Jane Austen",
  "Charles Dickens",
  "Mark Twain",
  "Leo Tolstoy",
  "Arthur Conan Doyle",
  "H. G. Wells",
  "Jules Verne",
  "Edgar Allan Poe",
  "Herman Melville",
  "Fyodor Dostoevsky",
  "Oscar Wilde",
  "George Bernard Shaw",
  "Mary Shelley",
  "Lewis Carroll",
  "Robert Louis Stevenson",
  "Nathaniel Hawthorne",
  "Henry James",
  "Joseph Conrad",
  "Rudyard Kipling",
];
